#if !(defined(GO) && defined(GOM) && defined(GO2) && defined(DATA))
#error Meh...
#endif

GO(swresample_configuration, pFv)
GO(swresample_license, pFv)
GO(swresample_version, uFv)
GO(swr_alloc, pFv)
GO(swr_alloc_set_opts2, iFppiipiiip)
GO(swr_build_matrix2, iFppdddddplip)
GO(swr_close, vFp)
GO(swr_config_frame, iFppp)
GO(swr_convert, iFppipi)
GO(swr_convert_frame, iFppp)
GO(swr_drop_output, iFpi)
GO(swr_free, vFp)
GO(swr_get_class, pFv)
GO(swr_get_delay, IFpI)
GO(swr_get_out_samples, iFpi)
GO(swr_init, iFp)
GO(swr_inject_silence, iFpi)
GO(swr_is_initialized, iFp)
GO(swr_next_pts, IFpI)
GO(swr_set_channel_mapping, iFpp)
GO(swr_set_compensation, iFpii)
GO(swr_set_matrix, iFppi)
